feat: 添加鲍信
DZDcyj/QSGS-v2-Lua pull request #925
Opened 2024-10-21 15:34 UTC by DZDcyj

## 拉取请求简述
添加新武将鲍信

### 处理议题内容
请在此部分添加处理的议题，以特殊词开头，例如 fix、resolve 等，注意数字后需要带空格，也可以通过 Github 自动补全完成这一步骤，如果没有，请删除本部分

Fixes #924 

## 检查项目
在本部分，您需要在以下的列表进行确认操作，您或许会在确认的过程中回忆起来可以改进的内容

以下是示例，在下列括号内打勾仅需要在方框内输入小写x即可

- [x] 我已充分阅读并理解相关规范

### 代码部分
- [x] 我确认代码已经测试通过
- [x] 我已经充分注释了我的代码，尤其是难以理解的部分
- [x] 我已经检查了代码并修复了错误的拼写
- [x] 我的代码已经经历过项目要求的格式化
- [x] 我的代码不会引入警告

### 文档规范
- [x] 我已经在文档中进行了充分的修改
- [x] 我的拉取请求标题符合对应的格式
- [x] 我已经关联了必要的标签和议题

2024-10-23 09:59 UTC, Rinkosanvsky requested changes

2024-10-23 09:59 UTC, Rinkosanvsky commented on lua/ai/ExpansionPackage-ai.lua
> +-- 应援选择目标
此处技能名称不是应援

2024-10-23 09:59 UTC, Rinkosanvsky commented on extensions/ExpansionPackage.lua
> +            data2:setValue(victim)
data2 变量未使用到，可以移除

2024-10-23 09:59 UTC, Rinkosanvsky commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
从体验的角度来看，这部分是否可以拆分 AI 和真人操作的情况？
AI 先选人再给牌，真人就效仿冯河的处理方式

2024-10-23 10:09 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
可参考界郭嘉给牌逻辑

2024-10-23 12:03 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
界郭嘉也是技能卡

2024-10-23 15:42 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
建议保持逻辑一致性

2024-10-24 08:19 UTC, DZDcyj reviewed
需要调整技能效果

2024-10-24 08:19 UTC, DZDcyj commented on lang/zh_CN/Package/ExpansionPackage.lua
> +    [':LuaYimou'] = '当一名角色受到伤害后，若你与其距离1以内，你可以选择一项令其执行之：1.从牌堆中获得一张【杀】；2.将一张手牌交给另一名角色，然后摸一张牌',
技能为 其与你 距离 1 之内，而非 你与其

2024-10-24 08:19 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +            if baoxin:distanceTo(victim) <= 1 then
distanceTo 的参数需要调整以适配实际技能效果

2024-10-26 01:54 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
> 从体验的角度来看，这部分是否可以拆分 AI 和真人操作的情况？
> AI 先选人再给牌，真人就效仿冯河的处理方式

从体验上来看应该将两个操作同时完成，考虑效仿刘琦的处理方式，先要求给牌，再判断有没有给出来，没有的时候进行第二次处理（即选人再给牌）

2024-10-27 07:46 UTC, DZDcyj commented on extensions/ExpansionPackage.lua
> +                    victim:drawCards(1, self:objectName())
可参考 askForYiji 方式处理

2024-10-28 14:14 UTC, Cactusssssssss approved these changes

2024-10-28 14:18 UTC, DZDcyj commented
当前测试有偶现 AI 问题，暂时遗留，以新 PR 跟踪
![image](https://github.com/user-attachments/assets/9e2758ee-c0fc-4ed5-bd4f-f730d8c3e92b)

2024-10-28 14:19 UTC, Rinkosanvsky approved these changes

2024-10-28 14:19 UTC, merged